import type { ElementType } from "react";
import {
  Squares2X2Icon,
  UsersIcon,
  BuildingOffice2Icon,
  CreditCardIcon,
  BanknotesIcon,
  ChartBarIcon,
  ChatBubbleLeftRightIcon,
  Cog6ToothIcon,
  ShieldCheckIcon,
  PaintBrushIcon,
  HeartIcon,
  DocumentTextIcon,
  KeyIcon,
  InformationCircleIcon,
  MegaphoneIcon,
  UserGroupIcon,
  ArrowTrendingUpIcon,
} from "@heroicons/react/24/outline";

export const navigationIcons: Record<string, ElementType> = {
  app: Squares2X2Icon,
  admin: ShieldCheckIcon,
  account: Cog6ToothIcon,
  dashboard: Squares2X2Icon,
  team: UserGroupIcon,
  plan: CreditCardIcon,
  credits: BanknotesIcon,
  activity: ChartBarIcon,
  messages: ChatBubbleLeftRightIcon,
  settings: Cog6ToothIcon,
  "admin-dashboard": Squares2X2Icon,
  users: UsersIcon,
  tenants: BuildingOffice2Icon,
  members: UserGroupIcon,
  plans: CreditCardIcon,
  financial: ArrowTrendingUpIcon,
  promotions: MegaphoneIcon,
  announcements: MegaphoneIcon,
  health: HeartIcon,
  logs: DocumentTextIcon,
  config: Cog6ToothIcon,
  api: KeyIcon,
  branding: PaintBrushIcon,
  about: InformationCircleIcon,
};
